import type { Metadata } from "next";
import "./globals.css";
import {JetBrains_Mono} from 'next/font/google'
import Header from "../../components/Header";
import Footer from "../../components/Footer";

export const metadata: Metadata = {
  title: "Monkey-Type clone",
  description: "Generated by create next app",
};

export const font = JetBrains_Mono({
    subsets: ['latin']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={'antialiased font.className bg-[#323437]'} cz-shortcut-listen="true">
            <Header/>      
            {children}
            <Footer/>
      </body>
    </html>
  );
}
